//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int ID { get; set; }
        public string VFPDriverID { get; set; }
        public string EmpNo { get; set; }
        public string FrmCode { get; set; }
        public string NameFirst { get; set; }
        public string NameLast { get; set; }
        public string NameMIddle { get; set; }
        public string SocialSec { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> CoTerminal { get; set; }
        public string Company { get; set; }
        public string Position { get; set; }
        public string NormDisp { get; set; }
        public string AddressLn1 { get; set; }
        public string AddressLn2 { get; set; }
        public string City { get; set; }
        public Nullable<int> State { get; set; }
        public string Zip { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public string AlternatePhone { get; set; }
        public string OtherPhone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<int> LicenseState { get; set; }
        public Nullable<int> LicenseType { get; set; }
        public Nullable<System.DateTime> Licenseexpire { get; set; }
        public Nullable<System.DateTime> EmploymentDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<int> DriverType { get; set; }
        public Nullable<System.DateTime> PhysicalExpire { get; set; }
        public string BadgeType { get; set; }
        public Nullable<System.DateTime> BadgeExpire { get; set; }
        public string BadgePendStat { get; set; }
        public Nullable<int> status { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedPrev { get; set; }
        public Nullable<System.DateTime> DateChangedPrev { get; set; }
        public string ChangedOld { get; set; }
        public Nullable<System.DateTime> DateChangedOld { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> dateDeleted { get; set; }
    
        public virtual DriverType DriverType1 { get; set; }
        public virtual licensetype licensetype1 { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual state state1 { get; set; }
        public virtual Terminal Terminal { get; set; }
    }
}
