//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrequencyDetail
    {
        public int ID { get; set; }
        public Nullable<int> HeaderID { get; set; }
        public Nullable<int> HolidayID { get; set; }
        public string VFPFreq_DtlId { get; set; }
        public string VFPFreqhedrid { get; set; }
        public string VFPHolidayId { get; set; }
        public string Monday { get; set; }
        public string Tuesday { get; set; }
        public string Wednesday { get; set; }
        public string Thursday { get; set; }
        public string Friday { get; set; }
        public string Saturday { get; set; }
        public string Sunday { get; set; }
        public Nullable<int> status { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedPrev { get; set; }
        public Nullable<System.DateTime> DateChangedPrev { get; set; }
        public string ChangedOld { get; set; }
        public Nullable<System.DateTime> DateChangedOld { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string VALID_BYNM { get; set; }
        public Nullable<System.DateTime> VALID_DTTM { get; set; }
        public string VALIDRECRD { get; set; }
    
        public virtual FrequencyHeader FrequencyHeader { get; set; }
        public virtual THoliday THoliday { get; set; }
    }
}
