//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schdl_gen
    {
        public int ID { get; set; }
        public Nullable<int> SCHDLGENID { get; set; }
        public Nullable<int> SCHEDULEID { get; set; }
        public string VFPSCHDLGENID { get; set; }
        public string VFPSCHEDULEID { get; set; }
        public string COTRIPNUMB { get; set; }
        public string CONTRACT { get; set; }
        public string TRIP { get; set; }
        public string STOPID { get; set; }
        public string NASS_CODE { get; set; }
        public Nullable<int> STOP_ORDER { get; set; }
        public string STOP_TYPE { get; set; }
        public string STOP_NAME { get; set; }
        public string ARRIVALTIM { get; set; }
        public string DEPARTTIME { get; set; }
        public Nullable<int> DRVRDAYNBR { get; set; }
        public string TRIPMASTID { get; set; }
        public string DRIVERNAME { get; set; }
        public string DRIVERSID { get; set; }
        public Nullable<System.DateTime> DATETRIP { get; set; }
        public string CHNGSTATUS { get; set; }
        public string COMMENTS { get; set; }
        public string STOPTYPE { get; set; }
        public Nullable<int> DRIVRCOD_N { get; set; }
        public Nullable<int> PO_DAYNBR { get; set; }
        public string POSTSTATUS { get; set; }
        public Nullable<System.DateTime> TRPBEGDATE { get; set; }
        public string TRPBEGTIME { get; set; }
        public string TRPBEGNASS { get; set; }
        public string TRPENDNASS { get; set; }
        public string SGMBEGNASS { get; set; }
        public string SGMENDNASS { get; set; }
        public Nullable<int> SMS_STAGE { get; set; }
        public string TRIPXPRTID { get; set; }
        public Nullable<System.DateTime> SGMARRVDTE { get; set; }
        public string TPXPRTORDR { get; set; }
        public Nullable<System.DateTime> ACTARIVTIM { get; set; }
        public Nullable<System.DateTime> ACTDPRTTIM { get; set; }
    }
}
