//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_Trips
    {
        public int ID { get; set; }
        public string VFPtripsid { get; set; }
        public Nullable<System.DateTime> datetrip { get; set; }
        public string co_trip { get; set; }
        public string co_term { get; set; }
        public string locstart { get; set; }
        public string locend { get; set; }
        public string showup { get; set; }
        public string timestart { get; set; }
        public string timeend { get; set; }
        public string endwork { get; set; }
        public Nullable<decimal> breaks { get; set; }
        public Nullable<decimal> sop { get; set; }
        public string driver { get; set; }
        public string VFPdriversid { get; set; }
        public string regular { get; set; }
        public string VFPregularid { get; set; }
        public string DRVRFILLIN { get; set; }
        public string VFPDRVRFILLID { get; set; }
        public string VFPfreqhedrid { get; set; }
        public Nullable<int> freqHeaderID { get; set; }
        public string tractor { get; set; }
        public string tractspecs { get; set; }
        public string trailer { get; set; }
        public string trailerloc { get; set; }
        public string checkin { get; set; }
        public string initial { get; set; }
        public string comments { get; set; }
        public string source { get; set; }
        public string VFPtripmasterid { get; set; }
        public Nullable<System.DateTime> moddatetim { get; set; }
        public string modnamelog { get; set; }
        public string moduserid { get; set; }
        public Nullable<System.DateTime> edittimein { get; set; }
        public string checkout { get; set; }
        public string initialout { get; set; }
        public Nullable<System.DateTime> edittimeout { get; set; }
        public string paid { get; set; }
        public Nullable<decimal> miles { get; set; }
        public Nullable<decimal> milesextra { get; set; }
        public string hoursextra { get; set; }
        public string extrdtrlat { get; set; }
        public Nullable<decimal> DUTY_HRS { get; set; }
        public Nullable<decimal> DRIVE_HRS { get; set; }
        public string createbynm { get; set; }
        public Nullable<System.DateTime> createdttm { get; set; }
        public string modprvbynm { get; set; }
        public Nullable<System.DateTime> modprvdttm { get; set; }
        public string modoldbynm { get; set; }
        public Nullable<System.DateTime> modolddttm { get; set; }
        public string deletebynm { get; set; }
        public Nullable<System.DateTime> deletedttm { get; set; }
        public string valid_bynm { get; set; }
        public Nullable<System.DateTime> valid_dttm { get; set; }
        public Nullable<int> validrecrd { get; set; }
        public Nullable<int> outloadpct { get; set; }
        public Nullable<int> in_loadpct { get; set; }
        public string TRACTOR_IN { get; set; }
        public string TRACTSPCIN { get; set; }
        public string TRAILER_IN { get; set; }
        public string TRAILLOCIN { get; set; }
        public Nullable<int> DRIVRCOD_N { get; set; }
        public Nullable<int> REGDRVCODN { get; set; }
        public string ROUTSTATUS { get; set; }
        public Nullable<int> tripmasterID { get; set; }
        public Nullable<int> DriversID { get; set; }
        public Nullable<int> DrvrFillID { get; set; }
    }
}
