//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_stops
    {
        public int ID { get; set; }
        public string VFPSTOPID { get; set; }
        public string NASS_CODE { get; set; }
        public string LOCATIONNM { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public string STOP_TYPE { get; set; }
        public string STOPTYPE { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<bool> IS_VALID { get; set; }
        public string CREATEBYID { get; set; }
        public Nullable<System.DateTime> CREATEDTTM { get; set; }
        public string MODNAMELOG { get; set; }
        public Nullable<System.DateTime> MODDATETIM { get; set; }
        public string MODPRVBYNM { get; set; }
        public Nullable<System.DateTime> MODPRVDTTM { get; set; }
        public string MODOLDBYNM { get; set; }
        public Nullable<System.DateTime> MODOLDDTTM { get; set; }
    }
}
