//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THoliday
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THoliday()
        {
            this.FrequencyDetails = new HashSet<FrequencyDetail>();
        }
    
        public int ID { get; set; }
        public string VFPHolidayId { get; set; }
        public string Ordering { get; set; }
        public Nullable<System.DateTime> DateHol { get; set; }
        public string Holiday { get; set; }
        public string Comments { get; set; }
        public Nullable<int> status { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedPrev { get; set; }
        public Nullable<System.DateTime> DateChangedPrev { get; set; }
        public string ChangedOld { get; set; }
        public Nullable<System.DateTime> DateChangedOld { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string Validbynm { get; set; }
        public Nullable<System.DateTime> Validdttm { get; set; }
        public string validrecord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrequencyDetail> FrequencyDetails { get; set; }
    }
}
