//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripMaster
    {
        public int ID { get; set; }
        public string VFPtripmasterid { get; set; }
        public Nullable<int> freqheadid { get; set; }
        public string VFPfreqhedrid { get; set; }
        public string cotripnumb { get; set; }
        public string coterminal { get; set; }
        public string podpartloc { get; set; }
        public string poarrivloc { get; set; }
        public string timbegwork { get; set; }
        public string timbegpro { get; set; }
        public string timendpo { get; set; }
        public string timendwork { get; set; }
        public Nullable<decimal> timebreak { get; set; }
        public Nullable<decimal> timework { get; set; }
        public string regdrivmon { get; set; }
        public string drivridmon { get; set; }
        public string regdrivtue { get; set; }
        public string drivridtue { get; set; }
        public string regdrivwed { get; set; }
        public string drivridwed { get; set; }
        public string regdrivthu { get; set; }
        public string drivridthu { get; set; }
        public string regdrivfri { get; set; }
        public string drivridfri { get; set; }
        public string regdrivsat { get; set; }
        public string drivridsat { get; set; }
        public string regdrivsun { get; set; }
        public string drivridsun { get; set; }
        public string tractor { get; set; }
        public string tractspecs { get; set; }
        public string trailer { get; set; }
        public Nullable<int> trailerlength { get; set; }
        public string trailerloc { get; set; }
        public Nullable<System.DateTime> begindate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string schednotes { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> moddatetim { get; set; }
        public string modnamelog { get; set; }
        public string moduserid { get; set; }
        public Nullable<int> mostrecent { get; set; }
        public Nullable<decimal> miles { get; set; }
        public string createbynm { get; set; }
        public Nullable<System.DateTime> createdttm { get; set; }
        public string modprvbynm { get; set; }
        public Nullable<System.DateTime> modprvdttm { get; set; }
        public string modoldbynm { get; set; }
        public Nullable<System.DateTime> modolddttm { get; set; }
        public string deletebynm { get; set; }
        public Nullable<System.DateTime> deletedttm { get; set; }
        public string valid_bynm { get; set; }
        public Nullable<System.DateTime> valid_dttm { get; set; }
        public Nullable<int> validrecrd { get; set; }
        public string drivwk2mon { get; set; }
        public string drivwk2tue { get; set; }
        public string drivwk2wed { get; set; }
        public string drivwk2thu { get; set; }
        public string drivwk2fri { get; set; }
        public string drivwk2sat { get; set; }
        public string drivwk2sun { get; set; }
        public string drivid2mon { get; set; }
        public string drivid2tue { get; set; }
        public string drivid2wed { get; set; }
        public string drivid2thu { get; set; }
        public string drivid2fri { get; set; }
        public string drivid2sat { get; set; }
        public string drivid2sun { get; set; }
    }
}
