//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripDriver
    {
        public int ID { get; set; }
        public Nullable<int> TripmasterID { get; set; }
        public Nullable<int> WeekID { get; set; }
        public Nullable<int> DayID { get; set; }
        public string DriverID { get; set; }
    }
}
