//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TRSEntities : DbContext
    {
        public TRSEntities()
            : base("name=TRSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<DriverNote> DriverNotes { get; set; }
        public virtual DbSet<DriverType> DriverTypes { get; set; }
        public virtual DbSet<FrequencyDetail> FrequencyDetails { get; set; }
        public virtual DbSet<FrequencyHeader> FrequencyHeaders { get; set; }
        public virtual DbSet<licensetype> licensetypes { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Security> Securities { get; set; }
        public virtual DbSet<sms_Trips> sms_Trips { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<Terminal> Terminals { get; set; }
        public virtual DbSet<THoliday> THolidays { get; set; }
        public virtual DbSet<TripMaster> TripMasters { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserNote> UserNotes { get; set; }
        public virtual DbSet<Schdl_gen> Schdl_gen { get; set; }
        public virtual DbSet<sms_schedule> sms_schedule { get; set; }
        public virtual DbSet<sms_stops> sms_stops { get; set; }
        public virtual DbSet<TripDriver> TripDrivers { get; set; }
    }
}
