//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserNotes = new HashSet<UserNote>();
        }
    
        public int ID { get; set; }
        public string VFPUserId { get; set; }
        public string UserLastName { get; set; }
        public string UserFirstName { get; set; }
        public string UserMiddleName { get; set; }
        public string UserLoginName { get; set; }
        public string Initials3 { get; set; }
        public string VFPOfficeLoc { get; set; }
        public Nullable<int> OfficeLoc { get; set; }
        public string VFPEditLevel { get; set; }
        public Nullable<int> Security { get; set; }
        public Nullable<int> UserActive { get; set; }
        public string password { get; set; }
        public string PasswordSalt { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> LastLoginTry { get; set; }
        public Nullable<int> status { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedPrev { get; set; }
        public Nullable<System.DateTime> DateChangedPrev { get; set; }
        public string ChangedOld { get; set; }
        public Nullable<System.DateTime> DateChangedOld { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string Validbynm { get; set; }
        public Nullable<System.DateTime> Validdttm { get; set; }
        public string validrecord { get; set; }
    
        public virtual Security Security1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNote> UserNotes { get; set; }
    }
}
